### ISSUE TITLE
data 폴더가 없을 경우

### ISSUE THREAD

**Issue by Sonchaegeon** [Yukong265/register#1]
![image](https://user-images.githubusercontent.com/64083083/120580525-4cd91180-c464-11eb-9d00-a03b3a120417.png)

![image](https://user-images.githubusercontent.com/64083083/120580092-88bfa700-c463-11eb-954e-456dc02d590f.png)

**폴더가 없을 경우**
- data라는 이름에 폴더를 생성해준다.

**Comment by Yukong265** [comment]
확인 후, 수정했습니다.
