### ISSUE TITLE
id가 중복될 경우

### ISSUE THREAD

**Issue by Sonchaegeon** [Yukong265/register#2]
![image](https://user-images.githubusercontent.com/64083083/120580723-9f1a3280-c464-11eb-8013-ee9d806de43f.png)

**id가 중복될 경우**
- 중복되었다고 알려주기
- 다시 회원가입으로 진입

**Comment by Yukong265** [comment]
Register과정을 함수로 만들어서 id가 중복 되었을 시에는 Already ID라고 알려주고 다시 Register함수를 부르게 하였습니다.
